/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_HMWindowGestionOuvrier (void);
GtkWidget* create_HMWindowAjouModif (void);
GtkWidget* create_HMwindowEnregistrer (void);
GtkWidget* create_HMWindowMessagederreur (void);
GtkWidget* create_HMWindowPresence (void);
GtkWidget* create_HMWindowMeilleurOuvrier (void);
GtkWidget* create_Acceuil (void);
GtkWidget* create_Capteurs (void);
GtkWidget* create_Ajout (void);
GtkWidget* create_Modification (void);
GtkWidget* create_Tester (void);
GtkWidget* create_Suppression (void);
GtkWidget* create_Alerte (void);
GtkWidget* create_Defect (void);
GtkWidget* create_Succes (void);
GtkWidget* create_Login (void);
GtkWidget* create_windowAMSTroupeaux (void);
GtkWidget* create_windowAffichage (void);
GtkWidget* create_windowAffnbrtroupeaux (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_dialog4 (void);
GtkWidget* create_dialog5 (void);
GtkWidget* create_Plantation (void);
GtkWidget* create_Plajouter (void);
GtkWidget* create_Plmodifier (void);
GtkWidget* create_Plsupprimer (void);
GtkWidget* create_Client (void);
GtkWidget* create_Clajouter (void);
GtkWidget* create_Clmodifier (void);
GtkWidget* create_Clsupprimer (void);
GtkWidget* create_Clfavoris (void);
GtkWidget* create_windowDashB (void);
