/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowAMSTroupeaux (void);
GtkWidget* create_windowAffichage (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_windowAffnbrtroupeaux (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_dialog3 (void);
GtkWidget* create_dialog4 (void);
GtkWidget* create_dialog5 (void);
